Update weight of vaFRAX
vesperfi/vesper-pool-ops pull request #50
Opened 2022-01-07 22:13 UTC by patidarmanoj10

2022-01-08 01:29 UTC, green-jeff requested changes
Leave 40% weight in Rari Fuse 6

55% Convex
40% Rari Fuse 6
5% Pool Buffer

2022-01-10 13:25 UTC, gabmontes reviewed
LGTM

2022-01-10 20:44 UTC, jgarzik approved these changes

2022-01-13 18:20 UTC, jcvernaleo approved these changes
OK

2022-01-13 18:23 UTC, merged