Exit Rari Fuse #18, Enter Convex Iron Bank
vesperfi/vesper-pool-ops pull request #63
Opened 2022-01-24 17:42 UTC by green-jeff

Exit Rari Fuse #18, enter curve-convex Iron Bank (Yearn lending protocol) This will provide theoretical APY of 6.05% APY / 4.85% for end user

2022-01-24 18:30 UTC, patidarmanoj10 commented
I would recommend exit pool 18 and move to Convex4 FRAXPool. That strategy is ready and getting good APY.

2022-01-25 02:59 UTC, jgarzik approved these changes

2022-01-25 16:24 UTC, patidarmanoj10 commented on mainnet/vaDAI.md
> +|Convex4 IronBank| 20% |
```suggestion
|Convex4 FRAXPool| 43% |
|Convex4 IronBank| 0% |
```

2022-01-25 16:25 UTC, patidarmanoj10 requested changes
Instead of adding new convex, should increase FRAX pool convex

2022-01-26 13:34 UTC, jcvernaleo requested changes
After PR #68 from @patidarmanoj10 this one now conflicts.  Could you either update it to only have the changes that don't touch vaDAI or close it and make a new one with the changes that are left?

2022-02-04 19:44 UTC, patidarmanoj10 commented
Outdated PR. will raise new PR if we want to update weight.

2022-02-04 19:44 UTC, closed without merging